### ISSUE TITLE
datapack may make server lag

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [GreenHexagon21/limboupgrade#1]
I ty your datapack and I think that's great, but i found when player loading many new chunk in LIMBO world it may make server very lag, tps and mspt will get really low(tps:5 mspt: 200)
is that my problem? or not, and i don't found any err logs in server

**Comment by mpustovoi** [comment]
How much RAM is allocated to your server?
From my experience, a minimum of 6 GB of RAM is required for a normal game with two or more friends, and best of 8 GB of RAM.
If you use Aternos, then you'd better give it up.. It can't even stand even vanilla servers with 2 players that are walking generating new chunks in different dimensions on the latest versions of Minecraft without drops to 5 TPS.

**Comment by xiaoyueyoqwq** [comment]
> How much RAM is allocated to your server?
> From my experience, a minimum of 6 GB of RAM is required for a normal game with two or more friends, and best of 8 GB of RAM.
> If you use Aternos, then you'd better give it up.. It can't even stand even vanilla servers with 2 players that are walking generating new chunks in different dimensions on the latest versions of Minecraft without drops to 5 TPS.

Understand, thanks for your support
